repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: black
    name: Code style formatting (black)
    language: system
    types: [python]
    pass_filenames: true
    entry: poetry run black
  - id: pylint
    name: Code linting (pylint)
    language: system
    types: [python]
    pass_filenames: true
    entry: poetry run pylint --rc-file=.pylintrc aira test/*
