name: Linting and codestyle

on:
  pull_request_target:
    types:
      - opened
    branches:
      - develop
      - stage
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: knowsuchagency/poetry-install@v2
      with:
        create-virtualenv: true
    - name: Install dependencies
      run: poetry install
    - name: Code style
      run: |
        poetry run black $(git ls-files '*.py')
    - name: Analysing the code with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')
